version: '3'
services:
  bench:
    build:
      context: ./isucon7-qualify
      dockerfile: ../docker/bench/Dockerfile
    image: isucon7-qualifier-bench
    depends_on:
      - web
    networks:
      - frontend
  web:
    build:
      context: ./isucon7-qualify
      dockerfile: ../docker/web/Dockerfile
      target: bench
    image: isucon7-qualifier-web-bench:nginx
    networks:
      - frontend
      - backend
    depends_on:
      - app
    ports:
      - "80:80"
  app:
    build:
      context: ./isucon7-qualify
      dockerfile: ../docker/app/nodejs/Dockerfile
    image: isucon7-qualifier-app-bench:nodejs
    networks:
      - backend
    depends_on:
      - db
    ports:
      - "5000"
    environment:
      ISUBATA_DB_USER: isucon
      ISUBATA_DB_PASSWORD: isucon
      ISUBATA_DB_HOST: db
  db:
    build:
      context: ./isucon7-qualify
      dockerfile: ../docker/db/Dockerfile
      target: analyze
    image: isucon7-qualifier-db-bench
    ports:
      - "3306"
    networks:
      - backend
    command: [ "--character-set-server=utf8mb4" ]
    environment:
      MYSQL_ALLOW_EMPTY_PASSWORD: "yes"
      #MYSQL_DATABASE: isubata
      #MYSQL_USER: isucon
      #MYSQL_PASSWORD: isucon
networks:
  frontend:
  backend:
